//addEvent('id', 'name');

addEvent('satDec302006', '*-P.K.Masters-*  Post-Christmas PK Trip');
addEvent('satDec232006', '*-P.K.Masters-*  Second Day of Fishing');
addEvent('satDec162006', '*-P.K.Masters-*  Forums Day');
addEvent('satDec92006', '*-P.K.Masters-*  War of the Levels');
addEvent('satNov252006', '*-P.K.Masters-*  PK Trip');
addEvent('satNov182006', '*-P.K.Masters-*  Lavaball War');
addEvent('satOct282006', '*-P.K.Masters-*  Pre-Halloween PK Trip');
addEvent('satOct212006', '*-P.K.Masters-*  Iron Warrior War');
addEvent('sunOct142006', '*-P.K.Masters-*  Day of Fishing');
addEvent('sunOct12006_2', '*-P.K.Masters-*  Unofficial Training Melee War');
addEvent('sunOct12006', '*-P.K.Masters-*  Unofficial Fart Bomb War');
addEvent('satSep302006', '*-P.K.Masters-*  First Bronze Warrior War');
addEvent('satSep162006', '*-P.K.Masters-*  vs. The Inhuman Knights');
addEvent('satSep92006', '*-P.K.Masters-*  PK Trip');
addEvent('satSep22006', '*-P.K.Masters-*  PK Trip');
addEvent('satAug192006', '*-P.K.Masters-*  First Water Balloon Fight');
addEvent('satJul292006', '*-P.K.Masters-*  First Snowball Fight');
addEvent('thuJul272006', '*-P.K.Masters-*  First Classic-PKer War');
addEvent('friJul212006', '*-P.K.Masters-*  First Fun Event Day');
addEvent('thuJul202006', '*-P.K.Masters-*  PK Trip');
addEvent('tueJul42006', '*-P.K.Masters-*  First Security Stronghold Trip');
addEvent('satJul152006', '*-P.K.Masters-*  Division: "ra" Accounts.  2nd Three-Day Streak (Day 3)');
addEvent('friJul142006', '*-P.K.Masters-*  Division: "ra" Accounts.  2nd Three-Day Streak (Day 2)');
addEvent('thuJul132006', '*-P.K.Masters-*  Division: "ra" Accounts.  2nd Three-Day Streak (Day 1)');
addEvent('tueJul112006', '*-P.K.Masters-*  2006 clan OLYMPICS');
addEvent('satJun242006', 'First  *-P.K.Masters-*  Black &amp; White Drop Party');
addEvent('satJun172006', 'First  *-P.K.Masters-*  vs. The Inhuman Knights');
addEvent('satJun102006', '*-P.K.Masters-*  vs.  *-P.K.Masters-*  Second Steel Warrior War');
addEvent('friJun92006', '*-P.K.Masters-*  vs.  *-P.K.Masters-*  First Steel Warrior War');
addEvent('satMay272006', '*-P.K.Masters-*  vs.  *-P.K.Masters-*  First Religious War');
addEvent('satApr192006', '*-P.K.Masters-*  vs.  *-P.K.Masters-*  First Assassin War');