/** News Archive for 2007
If no title, leave blank: ''

addNews('title', 'date', 'name', 'content');
*/

addNews('Event Update', 'Monday, December 31, 2007', 'Dbzruler72', '<div class="paragraph">The lack of updates for the past two months has come to a halt.  Today, almost all of the events since the last update have been added to the events page in the RuneScape section.  This includes six miniwar wins &amp; three holiday-related events.</div>');

addNews('Site Makeover', 'Friday, October 26, 2007', 'Dbzruler72', '<div class="paragraph">Tons of changes have been implemented over the clan website.  Most noticeably is the extreme change of background color.  There has been a graphical &amp; navigation change; graphics have been improved &amp; the navigation should now be clearer.  The polls page has been removed &amp; a poll has been moved to the homepage, which you can see in the bottom right corner.</div><div class="paragraph">The history pages of the parkour &amp; RuneScape sections have been <i>completely</i> revised.  Check those out if you want to read a much better version (with even more information).</div><div class="paragraph">Many new events have been added to the RuneScape section, so have fun with those.  The Picture of the Month &amp; Theme of the Month for RuneScape will be updated in November, as there won\'t be any time to update them until then.  Have fun with the new look!</div>');

addNews('Website Down', 'Friday, October 12, 2007', 'Dbzruler72', '<div class="paragraph">Many have noticed that the website has not been loading well or not loading at all for the past three weeks.  That problems was resolved last week, but you may still experience slow loading.  Almost all the links will be unavailable until there\'s enough time to fix them.</div>');
 - 
addNews('Event Updates', 'Saturday, September 22, 2007', 'Dbzruler72', '<div class="paragraph">It has been quite a while since the last update.  To make up for this, I\'ve added mostly all the events in from August &amp; September.  Unfortunately, not all September events were recorded properly, so they will not be added.</div>');

addNews('Militos Deci versus Tal Shiar Alliance', 'Monday, July 23, 2007', 'Dbzruler72', '<div class="paragraph">Militos Deci &amp; Tal Shiar Alliance went to war yesterday.  Militos Deci invited  *-P.K.Masters-*  to help.  The war was crashed, &amp; later decided as a draw.  All the pictures, information, &amp; video are on the events page in the RuneScape section.</div>');

addNews('War &amp; Theme of the Month', 'Wednesday, July 18, 2007', 'Dbzruler72', '<div class="paragraph">After a week or so of preparation, we warred Saradomin\'s Army yesterday.  It was crashed, but find out who did on the events page in the RuneScape section.  The war\'s pictures, attendance, notes, video, etc. are all in the RuneScape section too.</div><div class="paragraph">This month\'s Theme of the Month had been voted on earlier this month, but I haven\'t been able to post up the story until today.  In this Theme of the Month story, u will find that a new type of players arise very early in RuneScape.</div>');

addNews('Abridged Azure', 'Saturday, June 23, 2007', 'Dbzruler72', '<div class="paragraph">June\'s Theme of the Month event took place today.  What a blue war it was.  To see all pictures, the video, &amp; other information check out the events page in the RuneScape section.</div>');

addNews('Speed &amp; Security', 'Tuesday, June 12, 2007', 'Dbzruler72', '<div class="paragraph">In yesterday\'s update, I mentioned the website having a huge update that would make loading time very small.  As u navigate, the pages should load much faster than before.  U will see that the effects on images &amp; some links are gone--this is part of the update.  Navigation has been optimized for 56k connections &amp; slow processors.</div><div class="paragraph">Better security has also been implemented.  In the Terms of Use, it clearly states JavaScript must be enabled at all times while on the  *-P.K.Masters-*  website.  Apparently, some user don\'t think the Terms of Use apply to them.  Therefore, the website is now under heavy security.  So don\'t try to pull anymore tricks!</div><div class="paragraph">The Theme of the Month archives in the RuneScape section have been modified to specificlally fit the years.  I hope that should shrug off some confusion.  U will also notice that the Recent Updates section (the one u are reading now) has been changed a little.  This will attract more attention to the latest updates.</div><div class="paragraph">On a final note, if any problems occur on the website at all, please <a href="mailto:Dbzruler72@hotmail.com">report the bug to me</a>.  U may find that some links are broken or are directed to the wrong place.</div>');

addNews('', 'Monday, June 11, 2007', 'Dbzruler72', '<div class="paragraph">Quite a few updates are being added in today.  To start, a planned PK Run-In against a team lead by Tmmc2 happened Saturday, June 9, 2007.  Check out the interesting details on the events page in the RuneScape section.  CTET hosted another event: Summer Day.  Hot it was, but we cooled off with a Water Balloon Fight to end our exciting day.  The information, pictures, &amp; videos of those two events can be found on the events page in the RuneScape section.  In other news, over the next week there will be a huge update which will increase loading time significantly.  This should fix the problems some users have been having.</div>');

addNews('', 'Monday, June 4, 2007', 'Dbzruler72', '<div class="paragraph">Tip.It\'s very own CTET hosted Clan Pyro-Mania!  *-P.K.Masters-*  was one of the four clans that entered.  Did we end up standing in the spotlight or standing a step down from the winning clan congratulating them?  Check out the event on the events page in the RuneScape section.</div>');

addNews('', 'Saturday, May 26, 2007', 'Dbzruler72', '<div class="paragraph">An official PK Trip was held earlier today.  Why not check it out on the events page in the RuneScape section?</div>');

addNews('', 'Monday, May 21, 2007', 'Dbzruler72', '<div class="paragraph">The second annual Multi Site Steel War took place Saturday, May 19, 2007.  *-P.K.M-* of course attended, supporting Tip.It.  RuneScape Community ended up winning.  This event\'s information &amp; pictures have been added to the events page in the RuneScape section.</div>');

addNews('', 'Wednesday, May 16, 2007', 'Dbzruler72', '<div class="paragraph">We\'ve been having a little fun lately, &amp; Mickyb13 ended up submitting a pretty funny, edited picture for this month\'s Picture of the Month.  Anxious to read this month\'s Theme of the Month story?  It\'s currently being developed because it\'s actually two in one.  Never has this happened before, but it is planned to have a nice twist.</div>');

addNews('', 'Sunday, April 29, 2007', 'Dbzruler72', '<div class="paragraph">An unofficial PKtrip last week led to a successful turnout.  We ran into TeamSweden.  Then "Rf" logged in &amp; ended it.  Later that day, we won a PK Run-In with Clan Hopeless which scattered after five or so minutes after two casualties.  Yesterday, the Theme of the Month event was the Two-Handed war.  Before that, we held a funeral for an ex-clan member: Justrs.  All information on both events can be found on the events page in the RuneScape section.</div>');

addNews('', 'Tuesday, April 17, 2007', 'Dbzruler72', '<div class="paragraph">First of all, since a security update a while ago, many users have suddenly had problems viewing the website.  They would get the "404 error" page.  This should now be fixed.  The three pictures that give access to the three sections of the website have also been updated.  They no longer have that annoying feeling from the switching of text.  Finally, the history page in the Parkour/Free Running section has been added.  I had actually typed the history a few months back but never had time to add it to the website.  Enjoy reading my Parkour history!</div>');

addNews('', 'Monday, April 9, 2007', 'Dbzruler72', '<div class="paragraph">April\'s Picture of the Month has been updated.  The Theme of the Month for April has also been updated.  What lurks at night in Falador?  Check out April\'s Theme of the Month to find out.</div>');

addNews('', 'Thursday, March 15, 2007', 'Dbzruler72', '<div class="paragraph">After the mysterious new section of the clan website, everyone will now know what it\'s all about.  The first  *-P.K.Masters-*  Parkour &amp; Free Running video has been released.  Go check out the events page on the Parkour/Free Running section.  Enjoy!</div>');

addNews('', 'Saturday, March 10, 2007', 'Dbzruler72', '<div class="paragraph">There will be no Theme of the Month this month, we\'ve been having problems &amp; are now recovering.  Nonetheless, I have found time to make navigation a bit easier &amp; faster.  The events page for RuneScape are now categorized by years.  This should reduce the loading time significantly &amp; the page requires less scrolling.  The news archives on the homepage have also been reordered by years.  Also, an official PKtrip has been added to the RuneScape events page.  Wondering where February\'s Theme of the Month event is?  I actually haven\'t been able to get to it yet, so it will be added soon.  Stated in previous news entries, Pictures of the Month will only be clan-related from now on.  So this month\'s Picture of the Month has been added.  There has also been a change to the clan members/allies/enemies page.  It\'s getting to be a hassle updating the page over &amp; over again each time a new member joins.  So, the page will just have to be the  *-P.K.Masters-*  RSHSC page.</div>');

addNews('', 'Sunday, February 24, 2007', 'Dbzruler72', '<div class="paragraph">Sorry it\'s late, but I have finally found time to put up February\'s Theme of the Month story.  Enjoy!  The  *-P.K.Masters-*  chat page is a bit different now.  U should no longer have to download SwiftSwitch or mIRC to enter the chat.  All u have to do now is put in the correct chat channel &amp; screen name &amp; u can chat with the clan.</div>');

addNews('', 'Thursday, February 1, 2007', 'Dbzruler72', '<div class="paragraph">I\'ve been pretty busy for the last month, so I\'m sorry there haven\'t been any new updated.  Let\'s start with an announcement about the Picture of the Month.  This is the last month that non-clan-related pictures will be the Picture of the Month.  Starting March, the Picture of the Month will be clan-related.  Three new events have been added to the events page on the RuneScape section of the clan website.  "ra" accounts are back so for those "ra" fans, enjoy!  For those who have been keeping up with RuneScape clan news, u may have heard that the OoC <font size="1">(Order of Cabbage)</font> had reached two million cabbage.  Because of their great achievement, January\'s Theme of the Month was cabbage.  Speaking of the Theme of the Month, voting is still underway for February\'s Theme of the Month.  The story will come out soon.</div>');

addNews('', 'Monday, January 1, 2007', 'Dbzruler72', '<div class="paragraph">Time to start the new year off right.  Liked the Pre-Halloween PKtrip?  We decided to have a Post-Christmas PKtrip.  This PKtrip had less clan members attending than usual, but it was successful.  The  *-P.K.Masters-*  Post-Christmas PKtrip is now on the events page of the RuneScape section of the clan website.  We had a few run-ins so enjoy those.  The pics, video, &amp; rest of info is on there as well.  January\'s Theme of the Month story has been added to the Theme of the Month page of the RuneScape section of the website.  Have a jolly <i>green</i> time reading it!</div>');